# Generated by pointblank

tbl <- read_csv(here("data_cleaned", "daily_precip.csv"), col_types = cols(site = col_character()))

test_that("column `date` is of type: Date", {

  expect_col_is_date(
    tbl,
    columns = vars(date),
    threshold = 1
  ) 
})

test_that("column `site` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(site),
    threshold = 1
  ) 
})

test_that("column `observer` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(observer),
    threshold = 1
  ) 
})

test_that("column `notes` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(notes),
    threshold = 1
  ) 
})

test_that("column `flag` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(flag),
    threshold = 1
  ) 
})

test_that("column `doy` is of type: numeric", {

  expect_col_is_numeric(
    tbl,
    columns = vars(doy),
    threshold = 1
  ) 
})

test_that("column `precip` is of type: numeric", {

  expect_col_is_numeric(
    tbl,
    columns = vars(precip),
    threshold = 1
  ) 
})

test_that("values should agree with the given R expression", {

  expect_col_vals_expr(
    tbl,
    expr = ~hms::is_hms(time),
    threshold = 0.2
  ) 
})

test_that("values in `flag` should be in the set of `A`, `U`, `T` (and 2 more)", {

  expect_col_vals_in_set(
    tbl,
    columns = vars(flag),
    set = c("A", "U", "T", "E", NA),
    threshold = 0.2
  ) 
})

test_that("values should agree with the given R expression", {

  expect_col_vals_expr(
    tbl,
    expr = ~case_when(flag != "A" ~ between(precip, 0, 300)),
    # label = "Is rainfall ever above 300mm in a single day?",
    threshold = 0.2
  ) 
})

test_that("values in `doy` should be between `1` and `366`", {

  expect_col_vals_between(
    tbl,
    columns = vars(doy),
    left = 1,
    right = 366,
    threshold = 0.2
  ) 
})

test_that("values in `cor` (computed column) should be > `0.4`. Precondition applied: ``%>%`(...)`", {
  
  expect_col_vals_gt(
    tbl,
    columns = vars(cor),
    value = 0.4,
    na_pass = TRUE,
    preconditions = ~. %>% 
      pivot_wider(date, names_from = site, values_from = precip) %>% 
      select(-date) %>% 
      cor(use = "pairwise.complete.obs", method = "spearman") %>% 
      as_tibble(rownames = "site") %>% 
      pivot_longer(-site, names_to = "site2", values_to = "cor") 
  )
})

test_that("any duplicate dates within sites?", {

  expect_col_vals_equal(
    tbl,
    columns = vars(duped),
    value = "FALSE",
    preconditions = ~. %>% group_by(site) %>% mutate(duped = duplicated(date)) %>% ungroup()
  )
})

